databases:
  - name: postgres
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: rails
    env: ruby
    repo: https://github.com/jumpstart-pro/jumpstart-pro
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

